name: Regenerate README file

on:
  push:
    branches:
      - master
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron:  '0 0 * * *'

jobs:

  regenerate-readme: #----------------------------------------------------------
    name: Regenerate README.md file
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up PHP envirnoment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Configure git user
        run: |
          git config --global user.email "alain.schlesser@gmail.com"
          git config --global user.name "Alain Schlesser"

      - name: Check if remote branch exists
        id: remote-branch
        run: echo ::set-output name=exists::$([[ -z $(git ls-remote --heads origin sync-spec-test-suite) ]] && echo "0" || echo "1")

      - name: Create branch to base pull request on
        if: steps.remote-branch.outputs.exists == 0
        run: |
          git checkout -b sync-spec-test-suite

      - name: Fetch existing branch to add commits to
        if: steps.remote-branch.outputs.exists == 1
        run: |
          git fetch --all --prune
          git checkout sync-spec-test-suite
          git pull --no-rebase

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          sudo chmod +x /usr/local/bin/wp

      - name: Install scaffold-package command
        run: |
          wp package install wp-cli/scaffold-package-command

      - name: Regenerate README.md file
        run: |
          wp scaffold-package --readme --force .

      - name: Check if there are changes
        id: changes
        run: echo ::set-output name=changed::$([[ -z $(git status --porcelain) ]] && echo "0" || echo "1")

      - name: Commit changes
        if: steps.changes.outputs.changed == 1
        run: |
          git add --all .
          git commit -m "Regenerate README file - $(date +'%Y-%m-%d')"
          git push origin sync-spec-test-suite

      - name: Create pull request
        if: |
          steps.changes.outputs.changed == 1 &&
          steps.remote-branch.outputs.exists == 0
        uses: repo-sync/pull-request@v2
        with:
          source_branch: regenerate-readme
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Regenerate README file
          pr_body: "**This is an automated pull-request**\n\nRefreshes the `README.md` file with the latest changes to the docblocks in the source code."
          pr_reviewer: schlessera
          pr_label: scope:documentation
